### ISSUE TITLE
The SCM URL MUST start with the SCM provider, i.e. "git:..."

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/node-scm-source#2]
See for example https://github.com/zalando-stups/lein-scm-source/blob/master/src/leiningen/scm_source.clj#L19

Reference section in the docs: http://docs.stups.io/en/latest/user-guide/application-development.html#docker

**Comment by prayerslayer** [comment]
Thanks for spotting.

**Comment by prayerslayer** [comment]
Fixed with `0.2.1`.
